CREATE TABLE obitos (
    /* CAUSAS */
    COVID INT,
    SRAG INT,
    PNEUMONIA INT,
    INSUFICIENCIA_RESPIRATORIA INT,
    SEPTICEMIA INT,
    INDETERMINADA INT,
    OUTRAS INT,
    /* LOCAL */
    CIDADE TEXT,
    ESTADO TEXT,
    LUGAR TEXT,
    /* DATA */
    DIA DATE
);