CREATE TABLE IF NOT EXISTS obitos (
    /* CAUSAS */
    COVID INT NOT NULL DEFAULT 0,
    SRAG INT,
    PNEUMONIA INT,
    INSUFICIENCIA_RESPIRATORIA INT,
    SEPTICEMIA INT,
    INDETERMINADA INT,
    OUTRAS INT,

    /* LOCAL */
    CIDADE TEXT,
    ESTADO TEXT,
    LUGAR TEXT,
    
    /* DATA */
    DIA DATE
);